mod 'boxen', '0.0.26', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '3.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'prefpane', '1.20', :github_tarball => "indirect/puppet-prefpane"
